server:
  port: 8080
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sprout?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: sprout
    password: 2019133008
mybatis:
  type-aliases-package: com.example.demo.vo
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
app :
  kakao:
    rest-api-key: 285dc612b6af706b736a613b4da33ba5
    base-url: https://dapi.kakao.com
  openmeteo:
    base-url: https://api.open-meteo.com
    timezone: Asia/Seoul